import json

notebook_path = '/home/shimoiyusuke/manipulator-inverse-rl/IRL/Panda_Reach_v3_IRL.ipynb'

# Cell 1: Function Definition (id: c117cd26)
new_code_def = [
    "def projection_method_algorithm(env, expert_feature_expectation, expert_history=None, epsilon=0.001, m=2, n_episodes=500,\n",
    "                                opt_steps=10, batch_size=256, exploration_period=125, save_render=False, fps=5, print_every=50):\n",
    "    \n",
    "    feature_expectation = []\n",
    "    feature_expectation_bar = []\n",
    "    weights = []\n",
    "    margins = []\n",
    "    rewards = []\n",
    "    success_rates = []\n",
    "    all_results = [] \n",
    "    \n",
    "    obs_shape = env.observation_space['observation'].shape[0] + \\\n",
    "            env.observation_space['achieved_goal'].shape[0] + \\\n",
    "            env.observation_space['desired_goal'].shape[0]\n",
    "\n",
    "    max_runs = 2\n",
    "    \n",
    "    # Initialize Apprentice Agent ONLY ONCE\n",
    "    # User Request: Use 1 model for Apprentice, like Expert.\n",
    "    # We maintain the same object across iterations (warm start implicitly via object state).\n",
    "    apprentice = IRLTrainer(env=env, input_dims=obs_shape, agent_name='Apprentice', \n",
    "                            model_save_path='./Models/Apprentice/', \n",
    "                            exploration_period=exploration_period,\n",
    "                            batch_size=batch_size)\n",
    "\n",
    "    for i in range(max_runs):\n",
    "        print(f\"\\n-------------------------------------- Iteration: {i} --------------------------------------\\n\")\n",
    "        \n",
    "        # Calculate Reward Weights (Projection Method Logic)\n",
    "        if i == 0:\n",
    "             # Initial: Random Random Weights\n",
    "             observation, info = env.reset()\n",
    "             if isinstance(observation, dict):\n",
    "                 state = np.concatenate((observation['observation'], observation['achieved_goal'], observation['desired_goal']))\n",
    "             else:\n",
    "                 state = observation\n",
    "             sample_feature = torch.tensor(state, dtype=torch.float32)\n",
    "             w_0 = torch.randn(sample_feature.size(0), 1).div_(torch.randn(1).norm())\n",
    "             weights.append(w_0)\n",
    "             margins.append(1.0) # Placeholder\n",
    "        else:\n",
    "             # Calculate Projection\n",
    "             if i == 1:\n",
    "                feature_expectation_bar.append(feature_expectation[i - 1])\n",
    "                weights.append((expert_feature_expectation - feature_expectation[i - 1]).view(-1, 1))\n",
    "                margins.append((expert_feature_expectation - feature_expectation_bar[i - 1]).norm().item())\n",
    "             else:\n",
    "                A = feature_expectation_bar[i - 2]\n",
    "                B = feature_expectation[i - 1] - A\n",
    "                C = expert_feature_expectation - A\n",
    "                numerator = (B.view(-1, 1).t() @ C.view(-1, 1))\n",
    "                denominator = (B.view(-1, 1).t() @ B.view(-1, 1))\n",
    "                if denominator == 0: denominator = 1e-8\n",
    "                feature_expectation_bar.append(A + (numerator / denominator) * B)\n",
    "                weight = (expert_feature_expectation - feature_expectation_bar[i - 1]).view(-1, 1)\n",
    "                margin = (expert_feature_expectation - feature_expectation_bar[i - 1]).norm().item()\n",
    "                weights.append(weight)\n",
    "                margins.append(margin)\n",
    "             \n",
    "             print(f\"Margin: {margins[i]}\") \n",
    "             if margins[i] <= epsilon:\n",
    "                print(f\"Converged with margin {margins[i]} <= {epsilon}\")\n",
    "                break\n",
    "\n",
    "        # Train Apprentice\n",
    "        # Adjust exploration: Reduce for subsequent runs to exploit prior knowledge\n",
    "        if i == 0:\n",
    "            apprentice.exploration_period = exploration_period \n",
    "        else:\n",
    "            apprentice.exploration_period = 0\n",
    "        \n",
    "        # Clear Replay Buffer to allow training on new reward weights\n",
    "        # Critically important because the buffer contains old rewards which conflict with new weights\n",
    "        apprentice.memory.size = 0\n",
    "            \n",
    "        phase_name = f\"Apprentice_Iter{i}\" # Internal naming for files\n",
    "        print(f\"Phase: Apprentice (Iter {i}), Expl: {apprentice.exploration_period}\")\n",
    "\n",
    "        score_hist, avg_score_hist, success_hist, avg_success_hist = apprentice.irl_train(\n",
    "            n_episodes=n_episodes, opt_steps=opt_steps, \n",
    "            reward_weights=weights[-1], print_every=print_every, \n",
    "            plot_save_path=f'../Results/IRL/{phase_name}_Performance.png'\n",
    "        )\n",
    "        \n",
    "        # Save & Compute Features\n",
    "        apprentice.save_model()\n",
    "        apprentice_feature_expectation, apprentice_reward = compute_average_feature(agent=apprentice, m=m)\n",
    "        rewards.append(apprentice_reward)\n",
    "        feature_expectation.append(apprentice_feature_expectation)\n",
    "        \n",
    "        if save_render:\n",
    "            try:\n",
    "                apprentice.test_model(steps=1000, render_save_path=None)\n",
    "            except Exception as e:\n",
    "                print(f\"Rendering failed: {e}\")\n",
    "\n",
    "        # --- Live Plotting & Results Collection ---\n",
    "        final_sr = np.mean(success_hist[-100:]) * 100 if len(success_hist) >= 100 else 0.0\n",
    "        success_rates.append(final_sr)\n",
    "        \n",
    "        print(f\"Running Noise-Free Evaluation for Apprentice (Iter {i})...\")\n",
    "        eval_mean, eval_std, eval_sr, eval_succ_hist, eval_score_hist = evaluate_agent(apprentice, env, episodes=50, steps=200)\n",
    "        print(f\"Apprentice (Iter {i}) Evaluation: Success Rate {eval_sr:.1f}%, Return {eval_mean:.1f}\")\n",
    "        \n",
    "        res = {\n",
    "            \"id\": i, \"name\": phase_name,\n",
    "            \"success_history\": success_hist, \"score_history\": score_hist,\n",
    "            \"avg_success_history\": avg_success_hist,\n",
    "            \"chunk_stats\": calculate_chunked_stats(success_hist, chunk_size=50),\n",
    "            \"noise_free_success_rate\": eval_sr, \"eval_success_history\": eval_succ_hist, \"eval_score_history\": eval_score_hist,\n",
    "        }\n",
    "        all_results.append(res)\n",
    "        # --- Updated Plotting Logic ---\n",
    "        try:\n",
    "            # 1. Individual Plotting\n",
    "            plot_label = f\"Apprentice (Iter {i})\"\n",
    "            curr_sc = score_hist if 'score_hist' in locals() else []\n",
    "            curr_su = success_hist if 'success_hist' in locals() else []\n",
    "            print(f'Plotting Individual Result for {plot_label}...')\n",
    "            plot_individual_performance(plot_label, success_hist, score_hist)\n",
    "            \n",
    "            # 2. Comparative Plotting\n",
    "            # User Request: Expert and Apprentice... compare learning phase vs learning phase, and trained phase vs trained phase.\n",
    "            \n",
    "            # Learning Phase Comparison: Apprentice Training vs Expert Training\n",
    "            print(f'Plotting Comparison: Apprentice (Iter {i}) [Learning] vs Expert [Learning]...')\n",
    "            exp_su = expert_history if expert_history is not None else []\n",
    "            plot_comparative_dashboard(f'Comparison Learning Phase (Iter {i})', \n",
    "                {'name': 'Expert', 'scores': [], 'successes': exp_su}, \n",
    "                [{'name': f'Apprentice_Iter{i}', 'scores': score_hist, 'successes': success_hist}])\n",
    "            \n",
    "            # Trained Phase Comparison: Apprentice Eval vs Expert [Baseline]\n",
    "            if i > 0:\n",
    "                print(f'Plotting Comparison: Apprentice (Iter {i}) [Trained] vs Expert [Baseline]...')\n",
    "                plot_comparative_dashboard(f'Comparison Trained Phase (Iter {i})', \n",
    "                    {'name': 'Expert (Baseline)', 'scores': [], 'successes': exp_su}, \n",
    "                    [{'name': f'Apprentice_Iter{i}_Eval', 'scores': eval_score_hist, 'successes': eval_succ_hist}])\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"Plotting failed: {e}\")\n",
    "            import traceback\n",
    "            traceback.print_exc()\n",
    "\n",
    "        print(f\"Apprentice (Iter {i}) Final Avg Success Rate: {final_sr:.1f}%\")\n",
    "        print(f\"\\nDetailed Stats for Apprentice (Iter {i}):\")\n",
    "        stats = calculate_chunked_stats(success_hist, chunk_size=50)\n",
    "        print(f\"{'Chunk':<6} {'Range':<15} {'Success':<10} {'Fail':<10} {'Rate':<10}\")\n",
    "        print(\"-\" * 60)\n",
    "        for s in stats:\n",
    "            range_str = f\"{s['start_episode']}-{s['end_episode']}\"\n",
    "            print(f\"{s['chunk_idx']:<6} {range_str:<15} {s['success_count']:<10} {s['failure_count']:<10} {s['success_rate']*100:>6.2f}%\")\n",
    "        print(\"\")\n",
    "        \n",
    "        # --- NEW: Post-Training Evaluation (Noise-Free) ---\n",
    "    return rewards, margins, success_rates, all_results\n"
]

# Cell 2: Function Call (id: 79718e29)
new_code_call = [
    "# Execute IRL projection method for auto runs\n",
    "\n",
    "exp_hist = successes if 'successes' in locals() else []\n",
    "\n",
    "# Settings updated per user request:\n",
    "# - n_episodes: 500 \n",
    "# - exploration_period: 300 (Same as Expert)\n",
    "rewards, margins, success_rates, all_results = projection_method_algorithm(\n",
    "    env, \n",
    "    expert_feature_expectation, \n",
    "    expert_history=exp_hist, \n",
    "    n_episodes=500, \n",
    "    m=1000, \n",
    "    exploration_period=300\n",
    ")\n",
    "\n",
    "overall_success_rate = float(np.mean(success_rates)) if success_rates else 0.0\n",
    "print(f\"Overall success rate across {len(success_rates)} apprentices: {overall_success_rate:.1f}%\")\n"
]

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

found_def = False
found_call = False

for cell in nb['cells']:
    if cell.get('id') == 'c117cd26':
        cell['source'] = new_code_def
        found_def = True
    elif cell.get('id') == '79718e29':
        cell['source'] = new_code_call
        found_call = True
        
if not found_def:
    print("Definition cell (c117cd26) not found!")
if not found_call:
    print("Call cell (79718e29) not found!")

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Notebook updated successfully.")
