
import os
import sys
import numpy as np
from pathlib import Path

# Ensure current directory is in sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.append(current_dir)

import config
from config import SEED, N_EPISODES_APPRENTICE, NUM_APPRENTICES, EXPERT_TRAJECTORIES_PATH, FEATURE_EXPECTATION_EPISODES
from irl_utils import set_seed, create_env, get_obs_shape
import td3_runner
import gail_runner
import time
import compare_utils
from plotting import plot_comparative_dashboard

def main():
    print(f"\n{'='*80}")
    print(f"Running Compare_thesis.py with FIXED SEED = {SEED}")
    print(f"{'='*80}\n")

    # 1. Set Global Seed
    set_seed(SEED)

    # 2. Cleanup Expert Trajectories to ensure consistency with this seed
    if EXPERT_TRAJECTORIES_PATH.exists():
        try:
            os.remove(EXPERT_TRAJECTORIES_PATH)
            print(f"Deleted existing expert trajectories at {EXPERT_TRAJECTORIES_PATH}")
        except OSError as e:
            print(f"Error deleting expert trajectories: {e}")

    # --- Phase 1: Expert Training ---
    print("\n--- Phase 1: TD3 Expert Training ---")
    # Always ensure expert is trained/loaded consistent with config
    expert, expert_train_data = td3_runner.train_expert(n_episodes=config.N_EPISODES_EXPERT)
    
    # Add 'name' to expert_train_data for plotting
    expert_train_data['name'] = "TD3 Expert (Train)"
    
    time.sleep(2) # Allow cleanup

    # --- Phase 2: Apprentice Training (TD3 IRL) ---
    print("\n--- Phase 2: TD3 Apprentice Training (IRL) ---")
    
    env = create_env()
    obs_shape = get_obs_shape(env)

    # 2.1 Compute Expert Features
    print("Step 2.1: Computing Expert Features")
    expert_feature_expectation, _ = td3_runner.compute_expert_features(expert, env, m=FEATURE_EXPECTATION_EPISODES)

    # Initialize projection method variables
    feature_expectation = []
    feature_expectation_bar = []
    all_td3_train_results = []

    # 2.2 Train Apprentice 0
    print(f"Step 2.2: Training TD3 Apprentice 0 with Seed {SEED}")
    res0, feat0, w0, m0 = td3_runner.train_apprentice_0(env, obs_shape, seed=SEED)
    all_td3_train_results.append(res0)
    feature_expectation.append(feat0)

    # 2.3 Train Apprentice 1-N
    for i in range(1, NUM_APPRENTICES):
        print(f"Step 2.3.{i}: Training TD3 Apprentice {i} with Seed {SEED}")
        res, feat, w, m, new_bar, converged = td3_runner.train_apprentice_i(
            i, env, obs_shape, expert_feature_expectation, 
            feature_expectation, feature_expectation_bar, seed=SEED
        )
        
        if new_bar is not None:
            feature_expectation_bar.append(new_bar)
            
        if converged:
            print(f"TD3 Apprentices converged at iteration {i}")
            break
            
        all_td3_train_results.append(res)
        feature_expectation.append(feat)
        
    env.close() # Explicitly close Phase 2 env
    time.sleep(2)

    # 2.4 Evaluate TD3 Apprentices
    print("\n--- Evaluating TD3 Apprentices ---")
    td3_apprentice_eval_data = td3_runner.evaluate_apprentices()
    
    time.sleep(2)

    # --- Phase 3: GAIL Apprentice Training ---
    print("\n--- Phase 3: GAIL Apprentice Training ---")
    
    # Ensure expert trajectories exist (generated by train_expert if needed, or helper)
    gail_runner.ensure_expert_trajectories()
    
    all_gail_train_results = []

    # 3.1 Train GAIL Apprentice 1-N
    for i in range(1, NUM_APPRENTICES):
        print(f"Step 3.1.{i}: Training GAIL Apprentice {i} with Seed {SEED}")
        res = gail_runner.train_gail_apprentice_i(i, seed=SEED)
        all_gail_train_results.append(res)
    
    time.sleep(2)

    # 3.2 Evaluate GAIL Apprentices
    print("\n--- Evaluating GAIL Apprentices ---")
    gail_apprentice_eval_data = gail_runner.evaluate_apprentices()

    time.sleep(2)

    # --- Phase 4: Evaluation & Plotting ---
    print("\n--- Phase 4: Final Comparison & Plotting ---")

    # Evaluate Expert (for comparison baseline)
    print("Evaluating TD3 Expert...")
    _, td3_expert_eval_data_raw = td3_runner.evaluate_expert(expert)
    
    # Structure Expert Eval Data for Plotting
    expert_eval_data = {
        'name': 'TD3 Expert (Eval)',
        'scores': td3_expert_eval_data_raw['returns'],
        'successes': td3_expert_eval_data_raw['successes']
    }

    print("Generating Comparative Dashboard Plots...")
    results_dir = config.TD3_RESULTS_DIR.parent

    # Filter out Apprentice 0 for cleaner comparison (Focus on trained apprentices 1-N)
    td3_train_plot_data = [d for d in all_td3_train_results if d.get('id', 0) != 0]
    td3_eval_plot_data = [d for d in td3_apprentice_eval_data if d.get('id', 0) != 0]
    
    # GAIL usually starts from 1, but safe to filter
    gail_train_plot_data = [d for d in all_gail_train_results if d.get('id', 0) != 0]
    gail_eval_plot_data = [d for d in gail_apprentice_eval_data if d.get('id', 0) != 0]

    # 1. TD3 Training Comparison (Expert Train vs TD3 Apprentice Train)
    plot_comparative_dashboard(
        "TD3 Training Phase",
        expert_train_data,
        td3_train_plot_data,
        save_path=str(results_dir / "TD3_Training_Comparison.png")
    )
    
    # 2. TD3 Evaluation Comparison (Expert Eval vs TD3 Apprentice Eval)
    plot_comparative_dashboard(
        "TD3 Evaluation Phase",
        expert_eval_data,
        td3_eval_plot_data,
        save_path=str(results_dir / "TD3_Evaluation_Comparison.png")
    )

    # 3. GAIL Training Comparison (Expert Train vs GAIL Apprentice Train)
    plot_comparative_dashboard(
        "GAIL Training Phase",
        expert_train_data,
        gail_train_plot_data,
        save_path=str(results_dir / "GAIL_Training_Comparison.png")
    )

    # 4. GAIL Evaluation Comparison (Expert Eval vs GAIL Apprentice Eval)
    plot_comparative_dashboard(
        "GAIL Evaluation Phase",
        expert_eval_data,
        gail_eval_plot_data,
        save_path=str(results_dir / "GAIL_Evaluation_Comparison.png")
    )

    # 5. Final Combined Comparison (TD3 Eval vs GAIL Eval)
    # Note: Using existing utility but making sure we save it specifically
    expert_data, all_apprentices = compare_utils.prepare_final_comparison_data(
        td3_expert_eval_data_raw,
        td3_apprentice_eval_data,
        gail_apprentice_eval_data
    )

    # Plot
    save_path = config.TD3_RESULTS_DIR.parent / "TD3_vs_GAIL_Comparison_Thesis.png"
    plot_comparative_dashboard(
        "TD3 vs GAIL Evaluation Comparison (Thesis Seed)",
        expert_data,
        all_apprentices,
        save_path=str(save_path)
    )
    print(f"\nExperiment Complete. Comparison plot saved to: {save_path}")

if __name__ == "__main__":
    main()
